---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prom
resources:
  - source.yaml
  - namespace.yaml
  - grafana-persistent-volume.yaml
  - grafana-persistent-volume-claim.yaml
  - release.yaml
