---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nfs-server-provisioner
resources:
  - ../../base/nfs-server-provisioner
patchesStrategicMerge:
  - nfs-data-persistent-volume.yaml
