---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 10m0s
  path: ./infrastructure/cert-manager/helm-release
  prune: true
  validation: client
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
