---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nfs-ganesha-server-and-external-provisioner
spec:
  interval: 30m
  url: https://kubernetes-sigs.github.io/nfs-ganesha-server-and-external-provisioner/
